### PR TITLE
RNDOwned PR with fixed whitespace

### PR DESCRIPTION
**Pull request by mattwollf**
I think the whitespace indenting should be fixed.

### CODE REVIEW

**Comment by Master-Foo** [comment]
OK, I'll check it tomorrow.

**Comment by Master-Foo** [comment]
Looks good. Approved!

**Comment by Master-Foo** [comment]
BTW. What is the *.swp in .gitignore?

Obviously it's a backup file of some sort. (Assuming you put it in the correct section). What editor creates .swp backup files?

**Comment by mattwollf** [comment]
I keep having the problem where vim doesn't delete them on exit.

**Pull request merged**
